### ISSUE TITLE
g un pb chef!

### ISSUE THREAD

**Issue by atvictor** [LogiquePlurielle/test#1]
et pas un des moindre!

**Comment by emend** [comment]
Trying email answer
Le 26/01/2015 18:05, Victor a écrit :
>
> et pas un des moindre!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LogiquePlurielle/test/issues/1>.
>

-- 
Etienne Mendes
/CEO of Logique Plurielle/
/06.78.71.21.69
mendes.etienne@gmail.com/
